In [54]:
import pandas as pd
import re

In [55]:
urls_df = pd.read_csv('URLs.txt')
urls_df.head(10)

                                                 url
0                                            /world/
1                                           /latest/
2                                      /?updated=top
3  /politics/36188461-s-marta-zhizn-rossiyan-susc...
4  /world/36007585-tramp-pridumal-kak-reshit-ukra...
5  /science/36157853-nasa-sobiraet-ekstrennuyu-pr...
6  /video/36001498-poyavilis-pervye-podrobnosti-g...
7  /world/36007585-tramp-pridumal-kak-reshit-ukra...
8                                          /science/
9                                            /sport/

In [56]:
find_news = r'/\d{8}-'
urls_df[urls_df['url'].str.contains(find_news)]
urls_df.head(20)

# только я не понял, какого фига он нашел мне еще и /world/ и прочее, 
# при том, что в регулярке ЯВНО указано наличие 8 цифр подряд и даже на https://regex101.com/ строка
# /world/, очевидно, эту регулярку не проходит

                                                  url
0                                             /world/
1                                            /latest/
2                                       /?updated=top
3   /politics/36188461-s-marta-zhizn-rossiyan-susc...
4   /world/36007585-tramp-pridumal-kak-reshit-ukra...
5   /science/36157853-nasa-sobiraet-ekstrennuyu-pr...
6   /video/36001498-poyavilis-pervye-podrobnosti-g...
7   /world/36007585-tramp-pridumal-kak-reshit-ukra...
8                                           /science/
9                                             /sport/
10  /middleeast/36131117-divizion-s-400-ne-zametil...
11  /economics/36065674-rossiyane-vozmutilis-minim...
12  /politics/36118047-otets-24-detey-potreboval-i...
13  /travel/36194479-v-sheremetevo-passazhiry-ustr...
14  /politics/35638742-nesolidno-mariya-zaharova-s...
15  /video/36012692-tramp-otkrestilsya-ot-rossii-i...
16     /starlife/36174817-guzeeva-rasstalas-s-muzhem/
17  /health/36149308-predlozheno-prostoe-sredstvo-...
18  /science/36139723-set-vzbudorazhila-novost-o-s...
19  /cis/36229699-poroshenko-obyavil-vseukrainskiy...